name: Build kernel (non-ksu)

on:
  push:
    branches: [ mysterious ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            bc bison flex libssl-dev \
            libelf-dev libdw-dev libbpf-dev zlib1g-dev \
            cpio python3 rsync wget git zip \
            llvm lld cmake build-essential

      - name: Build pahole (>= 1.25 for --btf_features)
        run: |
          git clone -q --depth=1 --branch v1.31 https://github.com/acmel/dwarves.git /tmp/dwarves
          cd /tmp/dwarves
          mkdir -p build && cd build
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr ..
          make -s -j$(nproc --all)
          sudo make install
          pahole --version

      - name: Cache Clang Toolchain
        id: cache-clang
        uses: actions/cache@v4
        with:
          path: zyc-clang-16
          key: clang-16.0.6-20250721-release

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          max-size: "2G"
          key: kernel-ccache-${{ runner.os }}

      - name: Run build script
        run: |
          chmod +x ./ci/build_ci.sh
          ./ci/build_ci.sh

      - name: Pack & Upload AnyKernel3 zip
        uses: actions/upload-artifact@v4
        with:
          name: mysterious
          path: anykernel/

      - name: Upload Build log
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log

